version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app_new
hooks:
  BeforeInstall:
    - location: scripts/stop_and_clean.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: ubuntu
