version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app_live
hooks:
  BeforeInstall:
    - location: scripts/stop_and_clean.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/update_app.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/reload_app.sh
      timeout: 300
      runas: ubuntu
