name: Deploy Next.js site to Pages
on:
  push:
    branches: [main]
permissions:
  contents: read
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Install dependencies
        run: npm ci
      - name: Build the project
        run: npm run build
      - name: Prepare deployment artifact
        run: zip -r app.zip .
      - name: Upload build artifact for later use
        uses: actions/upload-artifact@v3
        with:
          name: app-zip
          path: app.zip
      - name: Set timestamp and commit_sha
        id: set-timestamp
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          COMMIT_SHA=${{ github.sha }}
          FILE_NAME=app-$TIMESTAMP-$COMMIT_SHA.zip
          echo "file_name=$FILE_NAME" >> $GITHUB_ENV
  upload-to-s3:
    runs-on: ubuntu-latest
    needs: build
    environment: Development
    steps:
      - name: Download build artifact from previous job
        uses: actions/download-artifact@v3
        with:
          name: app-zip
          path: ./
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Upload artifact to S3
        run: |
          aws s3 cp app.zip s3://demo-next-bucket/${{ needs.build.outputs.file_name }}
      - name: Copy latest version to S3
        run: |
          aws s3 cp s3://demo-next-bucket/${{ needs.build.outputs.file_name }} s3://demo-next-bucket/app-latest.zip
  deploy:
    runs-on: ubuntu-latest
    needs: upload-to-s3
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Trigger CodeDeploy deployment
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          COMMIT_SHA=${{ github.sha }}
          FILE_NAME=app-$TIMESTAMP-$COMMIT_SHA.zip
          aws deploy create-deployment \
            --application-name DemoNextApplication \
            --deployment-group-name DevelopmentInstances \
            --s3-location bucket=demo-next-bucket,key=${{ needs.build.outputs.file_name }},bundleType=zip
