name: Deploy Next.js site to Pages
on:
  push:
    branches: [main]
permissions:
  contents: read
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Zip build
        run: zip -r app.zip .
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Sync build output to S3
        run: |
          aws s3 cp app.zip s3://demo-next-bucket/app.zip
      - name: Trigger CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name DemoNextApplication \
            --deployment-group-name DevelopmentInstances \
            --s3-location bucket=your-bucket-name,key=app.zip,bundleType=zip
