name: Deploy Next.js site to Pages
on:
  push:
    branches: [do]
permissions:
  contents: read
  id-token: write
env:
  REPO_SECRET: ${{ secrets.REPO_SECRET }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check if secret is set
        run: |
          if [ -z "$REPO_SECRET" ]; then
            echo "REPO_SECRET is not set"
          else
            echo "REPO_SECRET is set"
          fi
      
      # - shell: bash
      #   env:
      #     REPO_SECRET: ${{ secrets.REPO_SECRET }}
      #   run: |
      #     echo "$REPO_SECRET" # this line, log your REPO_SECRET
      # - name: Deploy to DigitalOcean Droplet
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{secrets.SSH_HOST}}
      #     username: ${{secrets.SSH_USER}}
      #     key: ${{secrets.SSH_KEY}}
      #     script: echo "Hello World" > hello.txt
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.REPO_HOST}}
          username: ${{secrets.REPO_USER}}
          key: ${{secrets.REPO_SECRET}}
          source: "README.md"
          target: /home/deployer/website
