name: Deploy Next.js site to Pages
on:
  push:
    branches: [main]
permissions:
  contents: read
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm ci  
      - name: Build the project
        run: npm run build
      - name: Prepare deployment artifact
        run: zip -r app.zip .
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Upload artifact to S3
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          COMMIT_SHA=${{ github.sha }}
          aws s3 cp app.zip s3://demo-next-bucket/app-$TIMESTAMP-$COMMIT_SHA.zip
      - name: Trigger CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name DemoNextApplication \
            --deployment-group-name DevelopmentInstances \
            --s3-location bucket=demo-next-bucket,key=app-$TIMESTAMP-$COMMIT_SHA.zip,bundleType=zip
